version: '3' 

services: 
  app:
    container_name: app
    build: .
    #image: carlosocarvalho/microservice-docker-laravel:v2
    #entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 --timeout 40s ./.docker/entrypoint.sh
    networks: 
      - app-network
    volumes: 
      - ./:/var/www
    depends_on: 
      - db
      - redis
    # environment: 
    #   - DB_HOST=db
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root  
  nginx:
    container_name: app_web
    build: ./.docker/nginx
    tty: true
    ports: 
      - "8000:80"
    volumes: 
      - ./:/var/www  
    networks: 
      - app-network
    depends_on: 
      - app 
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
    volumes: 
      - ./.docker/db/data:/var/lib/mysql  
    networks: 
       - app-network
  redis:
    image: redis:5-alpine
    container_name: redis
    networks: 
       - app-network     
networks: 
  app-network:
     driver: bridge