version: '3' 

services: 
  app:
    container_name: app
    image: carlosocarvalho/microservice-docker-laravel:latest
    networks: 
      - app-network
    volumes: 
      - ./:/var/www
    depends_on: 
      - db  
  nginx:
    container_name: app_web
    build: ./.docker/nginx
    tty: true
    ports: 
      - "8000:80"
    volumes: 
      - ./:/var/www  
    networks: 
      - app-network
    depends_on: 
      - app 
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
    volumes: 
      - ./.docker/db/data:/var/lib/mysql  
    networks: 
       - app-network
  redis:
    image: redis:5-alpine
    container_name: redis
    networks: 
       - app-network     
networks: 
  app-network:
     driver: bridge