apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
      - name: app-deployment
        image: img-app-deployment
        command: ["/bin/sh", "-c", "ls -s /var/www /usr/share/nginx; php-fpm"]
        ports:
        - containerPort: 80
        env:
         - name: DB_PASSWORD
           value: root
        envFrom:
         - configMapRef: 
             name: app-config
        volumeMounts:
          - name: app-config
            mountPath: /var/www/.env
            subPath: .env

      volumes:
      - name: app-config
        configMap:
          name: app-config
          items:
           - key: env
             path: .env     

